version: '3.7'

services:
  timekeeper:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./timekeeper:/timekeeper
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
