# Generated by Django 4.1.5 on 2023-01-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_resetpwd',
            new_name='is_password_reset',
        ),
    ]
