# Generated by Django 4.1.3 on 2022-12-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(default='Wating Approval', max_length=20),
        ),
    ]
