# Generated by Django 4.1.3 on 2022-12-21 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='action',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
